export const menu = [
	{
		id: 1,
		field: "Double Mantul",
		name: "2 For 3 Cheeseburger",
		price: 39545,
	},
	{
		id: 2,
		field: "Double Mantul",
		name: "2 For 39 Cheeseburger + Mozzarella Cheeseburger",
		price: 39545,
	},
	{
		id: 3,
		field: "Double Mantul",
		name: "2 For 39 Cheeseburger + Royal Chicken Burger",
		price: 39545,
	},
	{
		id: 4,
		field: "Double Mantul",
		name: "2 For 39 Mozzarella Cheeseburger + Royal Chicken Burger",
		price: 39545,
	},
	{
		id: 5,
		field: "Kings Chicken",
		name: "Paket Spicy1",
		price: 45000,
	},
	{
		id: 6,
		field: "Kings Chicken",
		name: "Paket Crispy 1",
		price: 45000,
	},
	{
		id: 7,
		field: "Kings Chicken",
		name: "Paket Spicy 2",
		price: 45000,
	},
	{
		id: 8,
		field: "Kings Chicken",
		name: "Paket Crispy 2",
		price: 45000,
	},
	{
		id: 9,
		field: "Kings Chicken",
		name: "5 Pcs Ayam Crispy",
		price: 90000,
	},
	{
		id: 9,
		field: "Cheese Burger",
		name: "King Box Cheeseburger Regular",
		price: 50909,
	},
	{
		id: 9,
		field: "Cheese Burger",
		name: "King Deals Box Cheeseburger Supreme Regular",
		price: 71364,
	},
	{
		id: 9,
		field: "Cheese Burger",
		name: "King Box Double Mozzarella Cheeseburger Regular",
		price: 76364,
	},
	{
		id: 9,
		field: "Cheese Burger",
		name: "Mozzarella Cheeseburger",
		price: 36364,
	},
	{
		id: 9,
		field: "Cheese Burger",
		name: "Cheeseburger",
		price: 26818,
	},
];
